# -*- coding: utf-8 -*-
"""CodeTicTalkTopic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13p0PdECmgX0vo_3uDdyrAPADek04jJhZ
"""

# -*- coding: utf-8 -*-
# ============================================================
# BERTopic benchmark robuste: segmentation × embeddings
# Version F.C. au bureau du 3ème post discussion C.V.G.
# ============================================================
#
# INSTALLATION (au choix)
# ------------------------------------------------------------
# Option A - pip (recommandé)
#   pip install -U bertopic sentence-transformers hdbscan umap-learn pysrt \
#                 scikit-learn pandas numpy tqdm torch pyarrow
#
# Option B - conda (exemple)
#   conda install -c conda-forge pandas numpy scikit-learn umap-learn hdbscan tqdm pyarrow
#   pip install -U bertopic sentence-transformers pysrt torch
#
# Vérification GPU (optionnelle)
#   python -c "import torch; print(torch.cuda.is_available())"
#
# NOTES
# ------------------------------------------------------------
# - Le script utilise CUDA automatiquement si disponible.
# - Entrée attendue : dossier contenant des fichiers .srt
# - Sorties :
#   1) benchmark_models_segmentations.csv
#   2) segments_topics_global.csv
#   3) topic_info.csv
#   4) topic_top_words.json
#   5) per_show_csv/*.csv
#   6) bertopic_model/
#   7) selection_summary.txt
#   8) run_config.json
#   9) doc_embeddings.npy
#  10) doc_embeddings_index.csv
#
# ============================================================

import os
import re
import glob
import json
import gc
import random
import warnings
from dataclasses import dataclass, asdict
from typing import List, Dict, Tuple

import numpy as np
import pandas as pd
from tqdm import tqdm

import pysrt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import normalized_mutual_info_score, adjusted_rand_score

import torch
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from bertopic import BERTopic

warnings.filterwarnings("ignore", category=FutureWarning)

# ----------------------------
# Configuration
# ----------------------------

@dataclass
class Config:
    input_srt_dir: str = "/content/srt_cleaned"
    output_dir: str = "/content/topic_model_output"

    # Baseline + challenger
    embedding_models: Tuple[str, ...] = (
        "all-MiniLM-L6-v2",
        "BAAI/bge-large-en-v1.5",
    )

    # Reproductibilité
    random_state: int = 42

    # BERTopic/HDBSCAN/UMAP
    min_topic_size: int = 25
    hdbscan_min_cluster_size: int = 25
    hdbscan_min_samples: int = 10
    umap_n_neighbors: int = 15
    umap_n_components: int = 5
    umap_min_dist: float = 0.0

    # Vectorizer
    ngram_range: Tuple[int, int] = (1, 2)
    top_n_words: int = 10
    language: str = "english"  # IMPORTANT pour CountVectorizer stop_words

    # Benchmark
    block_sizes_seconds: Tuple[int, ...] = (30, 45, 60, 90)
    benchmark_runs: int = 3

    # Analyse confiance
    low_conf_threshold: float = 0.20

    # Export embeddings (recommandé)
    export_doc_embeddings: bool = True
    embeddings_batch_size: int = 64
    normalize_embeddings: bool = True

    # Sérialisation BERTopic
    save_embedding_model_in_bertopic: bool = False  # recommandé: False (artefact plus léger/portable)


CFG = Config()
os.makedirs(CFG.output_dir, exist_ok=True)


# ----------------------------
# Seeds / Device
# ----------------------------

def set_all_seeds(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def get_device() -> str:
    return "cuda" if torch.cuda.is_available() else "cpu"


# ----------------------------
# SRT utils
# ----------------------------

def srt_time_to_seconds(t) -> float:
    return t.hours * 3600 + t.minutes * 60 + t.seconds + (t.milliseconds / 1000.0)


def normalize_text(text: str) -> str:
    text = re.sub(r"<[^>]+>", " ", text)
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def read_srt_file(path: str) -> List[Dict]:
    subs = pysrt.open(path, encoding="utf-8", error_handling="ignore")
    rows = []
    for i, sub in enumerate(subs):
        txt = normalize_text(sub.text)
        if not txt:
            continue
        rows.append({
            "subtitle_idx": i,
            "start_sec": srt_time_to_seconds(sub.start),
            "end_sec": srt_time_to_seconds(sub.end),
            "text": txt
        })
    return rows


def build_blocks_from_subtitles(subs: List[Dict], block_size_sec: int) -> List[Dict]:
    if not subs:
        return []

    blocks = []
    block_end_target = subs[0]["start_sec"] + block_size_sec
    cur_texts = []
    cur_start = subs[0]["start_sec"]
    first_idx = subs[0]["subtitle_idx"]
    last_end = subs[0]["end_sec"]

    for row in subs:
        s, e, txt = row["start_sec"], row["end_sec"], row["text"]
        if s < block_end_target:
            cur_texts.append(txt)
            last_end = e
        else:
            merged = " ".join(cur_texts).strip()
            if merged:
                blocks.append({
                    "block_start_sec": cur_start,
                    "block_end_sec": last_end,
                    "text": merged,
                    "first_sub_idx": first_idx,
                    "last_sub_idx": row["subtitle_idx"] - 1
                })
            cur_texts = [txt]
            cur_start = s
            block_end_target = cur_start + block_size_sec
            first_idx = row["subtitle_idx"]
            last_end = e

    merged = " ".join(cur_texts).strip()
    if merged:
        blocks.append({
            "block_start_sec": cur_start,
            "block_end_sec": last_end,
            "text": merged,
            "first_sub_idx": first_idx,
            "last_sub_idx": subs[-1]["subtitle_idx"]
        })
    return blocks


def load_corpus_with_provenance(input_dir: str, block_size_sec: int) -> pd.DataFrame:
    files = sorted(glob.glob(os.path.join(input_dir, "*.srt")))
    if not files:
        raise FileNotFoundError(f"Aucun .srt dans: {input_dir}")

    all_rows = []
    for f in tqdm(files, desc=f"Lecture SRT ({block_size_sec}s)"):
        show_id = os.path.splitext(os.path.basename(f))[0]
        subs = read_srt_file(f)
        blocks = build_blocks_from_subtitles(subs, block_size_sec)
        for bi, b in enumerate(blocks):
            all_rows.append({
                "show_id": show_id,
                "block_id": bi,
                "block_size_sec": block_size_sec,
                "start_sec": b["block_start_sec"],
                "end_sec": b["block_end_sec"],
                "duration_sec": b["block_end_sec"] - b["block_start_sec"],
                "text": b["text"],
                "first_sub_idx": b["first_sub_idx"],
                "last_sub_idx": b["last_sub_idx"]
            })

    df = pd.DataFrame(all_rows)
    if df.empty:
        raise ValueError(f"Aucun bloc extrait depuis {input_dir}")
    return df


# ----------------------------
# BERTopic factory
# ----------------------------

def build_topic_model(cfg: Config, embedding_model_name: str, seed_shift: int = 0, device: str = "cpu") -> BERTopic:
    rs = cfg.random_state + seed_shift

    embedding_model = SentenceTransformer(embedding_model_name, device=device)

    umap_model = UMAP(
        n_neighbors=cfg.umap_n_neighbors,
        n_components=cfg.umap_n_components,
        min_dist=cfg.umap_min_dist,
        metric="cosine",
        random_state=rs
    )

    hdbscan_model = HDBSCAN(
        min_cluster_size=cfg.hdbscan_min_cluster_size,
        min_samples=cfg.hdbscan_min_samples,
        metric="euclidean",
        cluster_selection_method="eom",
        prediction_data=True
    )

    vectorizer_model = CountVectorizer(
        ngram_range=cfg.ngram_range,
        stop_words=cfg.language
    )

    topic_model = BERTopic(
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer_model,
        min_topic_size=cfg.min_topic_size,
        nr_topics="auto",
        calculate_probabilities=True,
        top_n_words=cfg.top_n_words,
        verbose=False
    )
    return topic_model


# ----------------------------
# Metrics
# ----------------------------

def outlier_ratio(topics: List[int]) -> float:
    arr = np.array(topics)
    return float(np.mean(arr == -1)) if len(arr) else 1.0


def n_topics_effective(topics: List[int]) -> int:
    return len(set([t for t in topics if t != -1]))


def approx_topic_diversity(topic_model: BERTopic, topk: int = 10) -> float:
    topics_dict = topic_model.get_topics()
    words = []
    n_topics = 0
    for tid, pairs in topics_dict.items():
        if tid == -1:
            continue
        n_topics += 1
        words.extend([w for w, _ in pairs[:topk]])
    if n_topics == 0:
        return 0.0
    return len(set(words)) / float(topk * n_topics)


def stability_metrics(list_topics: List[List[int]]) -> Dict[str, float]:
    if len(list_topics) < 2:
        return {"ari_mean": np.nan, "nmi_mean": np.nan}
    aris, nmis = [], []
    for i in range(len(list_topics)):
        for j in range(i + 1, len(list_topics)):
            y1, y2 = np.array(list_topics[i]), np.array(list_topics[j])
            aris.append(adjusted_rand_score(y1, y2))
            nmis.append(normalized_mutual_info_score(y1, y2))
    return {"ari_mean": float(np.mean(aris)), "nmi_mean": float(np.mean(nmis))}


# ----------------------------
# Fit
# ----------------------------

def fit_with_outlier_reduction(
    docs: List[str],
    cfg: Config,
    embedding_model_name: str,
    run_id: int = 0,
    device: str = "cpu"
):
    model = build_topic_model(cfg, embedding_model_name, seed_shift=run_id, device=device)
    topics, probs = model.fit_transform(docs)

    # Réduction outliers robuste (fallback si erreur)
    try:
        new_topics = model.reduce_outliers(docs, topics, strategy="embeddings")
        model.update_topics(docs, topics=new_topics)
        topics = new_topics
    except Exception as e:
        print(f"[WARN] reduce_outliers a échoué ({embedding_model_name}, run {run_id}): {e}")

    return model, topics, probs


# ----------------------------
# Benchmark
# ----------------------------

def benchmark_models_and_segmentations(cfg: Config, device: str) -> pd.DataFrame:
    rows = []

    for emb_name in cfg.embedding_models:
        print(f"\n=== Modèle: {emb_name} | device={device} ===")
        for bs in cfg.block_sizes_seconds:
            df = load_corpus_with_provenance(cfg.input_srt_dir, block_size_sec=bs)
            docs = df["text"].tolist()

            run_topics, run_outliers, run_n_topics, run_diversities = [], [], [], []

            for r in range(cfg.benchmark_runs):
                set_all_seeds(cfg.random_state + r)

                model, topics, probs = fit_with_outlier_reduction(
                    docs, cfg, embedding_model_name=emb_name, run_id=r, device=device
                )

                run_topics.append(topics)
                run_outliers.append(outlier_ratio(topics))
                run_n_topics.append(n_topics_effective(topics))
                run_diversities.append(approx_topic_diversity(model, topk=10))

                # Nettoyage mémoire
                del model, probs
                gc.collect()
                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

            stab = stability_metrics(run_topics)

            rows.append({
                "embedding_model": emb_name,
                "block_size_sec": bs,
                "n_docs": len(docs),
                "outlier_ratio_mean": float(np.mean(run_outliers)),
                "outlier_ratio_std": float(np.std(run_outliers)),
                "n_topics_mean": float(np.mean(run_n_topics)),
                "n_topics_std": float(np.std(run_n_topics)),
                "topic_diversity_mean": float(np.mean(run_diversities)),
                "ari_mean": stab["ari_mean"],
                "nmi_mean": stab["nmi_mean"],
            })

    return pd.DataFrame(rows).sort_values(["embedding_model", "block_size_sec"]).reset_index(drop=True)


def add_composite_score(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()

    def mm(x):
        x = np.array(x, dtype=float)
        mn, mx = np.nanmin(x), np.nanmax(x)
        if np.isclose(mx, mn):
            return np.ones_like(x) * 0.5
        return (x - mn) / (mx - mn)

    outlier_bad = mm(out["outlier_ratio_mean"])
    nmi_good = mm(out["nmi_mean"].fillna(out["nmi_mean"].mean()))
    ari_good = mm(out["ari_mean"].fillna(out["ari_mean"].mean()))
    div_good = mm(out["topic_diversity_mean"])

    out["composite_score"] = (1.8 * (1 - outlier_bad)) + (1.0 * nmi_good) + (0.8 * ari_good) + (0.7 * div_good)
    return out


def pick_best_combo(scored_df: pd.DataFrame) -> Tuple[str, int]:
    best = scored_df.sort_values("composite_score", ascending=False).iloc[0]
    return str(best["embedding_model"]), int(best["block_size_sec"])


# ----------------------------
# Final run
# ----------------------------

def run_final_pipeline(cfg: Config):
    device = get_device()
    print(f"[INFO] Device détecté: {device}")
    print(f"[INFO] CUDA available: {torch.cuda.is_available()}")
    if torch.cuda.is_available():
        print(f"[INFO] GPU: {torch.cuda.get_device_name(0)}")

    # Traçabilité config
    with open(os.path.join(cfg.output_dir, "run_config.json"), "w", encoding="utf-8") as f:
        json.dump(asdict(cfg), f, indent=2, ensure_ascii=False)

    print("\n1) Benchmark croisé segmentation × embeddings")
    bench_df = benchmark_models_and_segmentations(cfg, device=device)
    scored = add_composite_score(bench_df)

    bench_csv = os.path.join(cfg.output_dir, "benchmark_models_segmentations.csv")
    scored.to_csv(bench_csv, index=False, encoding="utf-8")
    print(f"[OK] Benchmark: {bench_csv}")

    best_model, best_bs = pick_best_combo(scored)
    print(f"\n[SELECTED] model={best_model} | block_size={best_bs}s")

    print("\n2) Run final sur meilleur couple")
    df = load_corpus_with_provenance(cfg.input_srt_dir, block_size_sec=best_bs)
    docs = df["text"].tolist()

    set_all_seeds(cfg.random_state + 999)
    model, topics, probs = fit_with_outlier_reduction(
        docs, cfg, embedding_model_name=best_model, run_id=999, device=device
    )

    # Confidence robuste
    if isinstance(probs, np.ndarray) and probs.ndim == 2 and probs.shape[0] == len(docs):
        max_prob = np.max(probs, axis=1)
    else:
        max_prob = np.full(shape=(len(docs),), fill_value=np.nan)

    df["embedding_model"] = best_model
    df["topic"] = topics
    df["topic_confidence"] = max_prob
    df["is_low_conf"] = np.where(
        np.isnan(df["topic_confidence"]),
        0,
        (df["topic_confidence"] < cfg.low_conf_threshold).astype(int)
    )
    df["topic_label_for_analysis"] = df["topic"].astype(str)
    df.loc[df["is_low_conf"] == 1, "topic_label_for_analysis"] = "LOW_CONF"

    # 2bis) Export embeddings documentaires (recommandé)
    emb_npy = None
    emb_index_csv = None
    if cfg.export_doc_embeddings:
        print("\n3) Calcul et export des embeddings documentaires")
        embedder = SentenceTransformer(best_model, device=device)
        doc_embeddings = embedder.encode(
            docs,
            batch_size=cfg.embeddings_batch_size,
            show_progress_bar=True,
            convert_to_numpy=True,
            normalize_embeddings=cfg.normalize_embeddings
        )

        emb_npy = os.path.join(cfg.output_dir, "doc_embeddings.npy")
        np.save(emb_npy, doc_embeddings)

        emb_index_cols = ["show_id", "block_id", "start_sec", "end_sec", "text"]
        emb_index_csv = os.path.join(cfg.output_dir, "doc_embeddings_index.csv")
        df[emb_index_cols].to_csv(emb_index_csv, index=False, encoding="utf-8")

        # nettoyage mémoire
        del embedder, doc_embeddings
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # Exports topics
    final_csv = os.path.join(cfg.output_dir, "segments_topics_global.csv")
    df.to_csv(final_csv, index=False, encoding="utf-8")

    per_show_dir = os.path.join(cfg.output_dir, "per_show_csv")
    os.makedirs(per_show_dir, exist_ok=True)
    for sid, g in df.groupby("show_id", sort=True):
        g.sort_values("block_id").to_csv(os.path.join(per_show_dir, f"{sid}_topics.csv"), index=False, encoding="utf-8")

    topic_info = model.get_topic_info()
    topic_info["embedding_model"] = best_model
    topic_info_csv = os.path.join(cfg.output_dir, "topic_info.csv")
    topic_info.to_csv(topic_info_csv, index=False, encoding="utf-8")

    topic_words = {}
    for tid in topic_info["Topic"].tolist():
        if tid == -1:
            continue
        topic_words[int(tid)] = model.get_topic(tid)[:cfg.top_n_words]
    topic_words_json = os.path.join(cfg.output_dir, "topic_top_words.json")
    with open(topic_words_json, "w", encoding="utf-8") as f:
        json.dump(topic_words, f, ensure_ascii=False, indent=2)

    model_dir = os.path.join(cfg.output_dir, "bertopic_model")
    model.save(
        model_dir,
        serialization="safetensors",
        save_ctfidf=True,
        save_embedding_model=cfg.save_embedding_model_in_bertopic
    )

    summary_txt = os.path.join(cfg.output_dir, "selection_summary.txt")
    top = scored.sort_values("composite_score", ascending=False).iloc[0]
    with open(summary_txt, "w", encoding="utf-8") as f:
        f.write(f"Device used: {device}\n")
        f.write(f"Best embedding model: {best_model}\n")
        f.write(f"Best block size (sec): {best_bs}\n")
        f.write(f"Embeddings exported: {cfg.export_doc_embeddings}\n")
        f.write(f"Embeddings normalized: {cfg.normalize_embeddings}\n")
        for col in ["outlier_ratio_mean", "n_topics_mean", "topic_diversity_mean", "ari_mean", "nmi_mean", "composite_score"]:
            f.write(f"- {col}: {top[col]}\n")

    print("\n[OK] Sorties générées")
    print(f"- {bench_csv}")
    print(f"- {final_csv}")
    print(f"- {topic_info_csv}")
    print(f"- {topic_words_json}")
    print(f"- {model_dir}")
    print(f"- {summary_txt}")
    if emb_npy:
        print(f"- {emb_npy}")
    if emb_index_csv:
        print(f"- {emb_index_csv}")


if __name__ == "__main__":
    srt_files = glob.glob(os.path.join(CFG.input_srt_dir, "*.srt"))
    if not srt_files:
        raise FileNotFoundError(
            f"Aucun .srt trouvé dans {CFG.input_srt_dir}. "
            "Ajoutez vos fichiers SRT puis relancez."
        )

    run_final_pipeline(CFG)